### ISSUE TITLE
🐛Bug - Search Crashes App

### ISSUE THREAD

**Issue by DylanHojnoski** [MichiganTechCoursesMobile/MTUCoursesAndroid#34]
**Describe the bug**
When searching for a course and and no courses are found if you hit the back arrow in the top left corner the app crashes.

**To Reproduce**
1. Go to courses
2. Click on search bar
3. Type until it says "No courses found with this filter"
4. Click back arrow in top left
5. The app crashes

**Expected behavior**
It closes the search bar.

**Screenshots / Screen recordings**
If applicable, add screenshots or screen recordings to help explain your problem.

**Versions (please complete the following information):**
 - Device: Samsung Galaxy A42
 - Android Version: Android 13
 - App Version v1.0.2

**Additional context**

**Comment by LarveyOfficial** [comment]
Interesting, I ran into this during development on the debug build, but I could never reproduce it on the release build on my own device.

I will investigate this further, maybe if I resolve the issue on the debug build it will resolve this. 🤞🏼

**Comment by LarveyOfficial** [comment]
I was able to stop the crashing from occurring on the debug build. Seems the issue may be related to some versions of Android and how they handle closing the keyboard when the searchbar disappears.

I will leave this issue open until I can verify this works on other devices, but I may startup a beta branch on Google Play for instances like this

**Comment by LarveyOfficial** [comment]
@DylanHojnoski v1.0.3 has been release on Google Play, please update and let me know if the issue still occurs.

**Comment by DylanHojnoski** [comment]
It is no longer crashing.
